# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'random_gui.ui',
# licensing of 'random_gui.ui' applies.
#
# Created: Tue Jul 30 00:09:46 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.select_period_CB = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.select_period_CB.setFont(font)
        self.select_period_CB.setObjectName("select_period_CB")
        self.select_period_CB.addItem("")
        self.select_period_CB.addItem("")
        self.select_period_CB.addItem("")
        self.select_period_CB.addItem("")
        self.gridLayout_2.addWidget(self.select_period_CB, 0, 1, 1, 1)
        self.randomize_PB = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setWeight(75)
        font.setBold(True)
        self.randomize_PB.setFont(font)
        self.randomize_PB.setObjectName("randomize_PB")
        self.gridLayout_2.addWidget(self.randomize_PB, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.group1_L = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group1_L.setFont(font)
        self.group1_L.setObjectName("group1_L")
        QtWidgets.QListWidgetItem(self.group1_L)
        QtWidgets.QListWidgetItem(self.group1_L)
        QtWidgets.QListWidgetItem(self.group1_L)
        QtWidgets.QListWidgetItem(self.group1_L)
        QtWidgets.QListWidgetItem(self.group1_L)
        self.verticalLayout.addWidget(self.group1_L)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.group2_L = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group2_L.setFont(font)
        self.group2_L.setObjectName("group2_L")
        QtWidgets.QListWidgetItem(self.group2_L)
        QtWidgets.QListWidgetItem(self.group2_L)
        QtWidgets.QListWidgetItem(self.group2_L)
        QtWidgets.QListWidgetItem(self.group2_L)
        QtWidgets.QListWidgetItem(self.group2_L)
        self.verticalLayout_2.addWidget(self.group2_L)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.group3_L = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group3_L.setFont(font)
        self.group3_L.setObjectName("group3_L")
        QtWidgets.QListWidgetItem(self.group3_L)
        QtWidgets.QListWidgetItem(self.group3_L)
        QtWidgets.QListWidgetItem(self.group3_L)
        QtWidgets.QListWidgetItem(self.group3_L)
        QtWidgets.QListWidgetItem(self.group3_L)
        self.verticalLayout_3.addWidget(self.group3_L)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.group4_L = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group4_L.setFont(font)
        self.group4_L.setObjectName("group4_L")
        QtWidgets.QListWidgetItem(self.group4_L)
        QtWidgets.QListWidgetItem(self.group4_L)
        QtWidgets.QListWidgetItem(self.group4_L)
        QtWidgets.QListWidgetItem(self.group4_L)
        QtWidgets.QListWidgetItem(self.group4_L)
        self.verticalLayout_4.addWidget(self.group4_L)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.group5_L = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group5_L.setFont(font)
        self.group5_L.setObjectName("group5_L")
        QtWidgets.QListWidgetItem(self.group5_L)
        QtWidgets.QListWidgetItem(self.group5_L)
        QtWidgets.QListWidgetItem(self.group5_L)
        QtWidgets.QListWidgetItem(self.group5_L)
        QtWidgets.QListWidgetItem(self.group5_L)
        self.verticalLayout_5.addWidget(self.group5_L)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.group6_L = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group6_L.setFont(font)
        self.group6_L.setObjectName("group6_L")
        QtWidgets.QListWidgetItem(self.group6_L)
        QtWidgets.QListWidgetItem(self.group6_L)
        QtWidgets.QListWidgetItem(self.group6_L)
        QtWidgets.QListWidgetItem(self.group6_L)
        QtWidgets.QListWidgetItem(self.group6_L)
        self.verticalLayout_6.addWidget(self.group6_L)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Random Group Creator", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Class Period:", None, -1))
        self.select_period_CB.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "2nd", None, -1))
        self.select_period_CB.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "3rd", None, -1))
        self.select_period_CB.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "4th", None, -1))
        self.select_period_CB.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "5th", None, -1))
        self.randomize_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Randomize!!!", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Group 1", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Group 2", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Group 3", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Group 4", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Group 5", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Group 6", None, -1))
